"""Stable public domain-contract API for the enterprise copilot."""

from copilot.contracts.approvals import ApprovalRequest
from copilot.contracts.artifacts import Artifact
from copilot.contracts.base import ContractModel, ImmutableContractModel, JsonObject
from copilot.contracts.enums import (
    ApprovalResolutionAction,
    ApprovalStatus,
    ArtifactType,
    CapabilityName,
    ErrorType,
    EvidenceType,
    ReportLanguage,
    RiskLevel,
    StepResultStatus,
    StepType,
    TaskStatus,
    TaskType,
    ToolResultStatus,
)
from copilot.contracts.errors import DomainError, TaskError
from copilot.contracts.evidence import (
    EvidenceAddResult,
    EvidenceContent,
    EvidenceItem,
    EvidenceLedgerSnapshot,
    EvidenceSourceReference,
    LineageEdge,
    LineageIssue,
    LineageTrace,
)
from copilot.contracts.observability import (
    HistogramSnapshot,
    MetricSnapshot,
    ObservabilityContext,
    PerformanceAnalysis,
    PerformanceWarning,
    SpanKind,
    SpanStatus,
    TraceSpan,
    TraceSummary,
)
from copilot.contracts.plans import RetryPolicy, StepResult, TaskPlan, TaskStep
from copilot.contracts.tasks import (
    ApprovalRequirement,
    ExpectedOutput,
    TaskConstraints,
    TaskContract,
    TaskRequest,
    TaskResult,
    TaskState,
)
from copilot.contracts.tools import (
    ToolApprovalPolicy,
    ToolCall,
    ToolDefinition,
    ToolIdempotency,
    ToolResult,
    ToolTimeout,
)
from copilot.contracts.verification import (
    CandidateResult,
    CitationClaim,
    ClaimType,
    DeliverableRecord,
    NumericClaim,
    VerificationCheck,
    VerificationContext,
    VerificationIssue,
    VerificationResult,
    VerificationSeverity,
    VerificationStatus,
)

__all__ = [
    "ApprovalRequest",
    "ApprovalRequirement",
    "ApprovalResolutionAction",
    "ApprovalStatus",
    "Artifact",
    "ArtifactType",
    "CapabilityName",
    "ContractModel",
    "DomainError",
    "ErrorType",
    "EvidenceContent",
    "EvidenceAddResult",
    "EvidenceItem",
    "EvidenceLedgerSnapshot",
    "EvidenceSourceReference",
    "EvidenceType",
    "ExpectedOutput",
    "ImmutableContractModel",
    "JsonObject",
    "HistogramSnapshot",
    "MetricSnapshot",
    "LineageEdge",
    "LineageIssue",
    "LineageTrace",
    "ReportLanguage",
    "ObservabilityContext",
    "PerformanceAnalysis",
    "PerformanceWarning",
    "RetryPolicy",
    "RiskLevel",
    "StepResult",
    "StepResultStatus",
    "StepType",
    "SpanKind",
    "SpanStatus",
    "TaskConstraints",
    "TaskContract",
    "TaskError",
    "TaskPlan",
    "TaskRequest",
    "TaskResult",
    "TaskState",
    "TaskStatus",
    "TaskStep",
    "TaskType",
    "ToolApprovalPolicy",
    "ToolCall",
    "ToolDefinition",
    "ToolIdempotency",
    "ToolResult",
    "ToolResultStatus",
    "ToolTimeout",
    "TraceSpan",
    "TraceSummary",
    "CandidateResult",
    "CitationClaim",
    "ClaimType",
    "DeliverableRecord",
    "NumericClaim",
    "VerificationCheck",
    "VerificationContext",
    "VerificationIssue",
    "VerificationResult",
    "VerificationSeverity",
    "VerificationStatus",
]
